require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

# New cops
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true


Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
    - "spec/**/*"
