---
version: "3"
services:
  app: &app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chasqui:cached
      - ./tmp/downloads:/chasqui/tmp/downloads
      - node_cache:/chasqui/node_modules
      - bundle_cache:/bundle
      - rails_cache:/chasqui/tmp/cache
      - packs:/chasqui/public/packs
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST

#  worker:
#    <<: *app
#    command: bash -c "bundle exec rake resque:work"
#    ports: []
#    depends_on:
#      - postgres
#      - redis
#    environment:
#      - QUEUE=*
#      - DB_HOST
#      - REDIS_URL

  postgres:
    image: "postgres:11-alpine"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  node_cache:
  bundle_cache:
  rails_cache:
  packs:
