#!/bin/bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker-compose -p chasqui down
docker-compose -p chasqui build
$DIR/run yarn install --check-files
$DIR/run /bin/bash -c "bundle check || bundle install -j4"
$DIR/run /bin/bash -c "bundle binstubs --all && bundle exec spring binstub --all"
$DIR/run /bin/bash -c "bin/rake db:exists && bin/rake db:migrate || bin/rails db:setup"

docker-compose -p chasqui up --remove-orphans
