default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://root:root@#{ENV.fetch("POSTGRES_HOST", "localhost")}:#{ENV.fetch("POSTGRES_PORT", "5432")}/chasqui_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://root:root@#{ENV.fetch("POSTGRES_HOST", "localhost")}:#{ENV.fetch("POSTGRES_PORT", "5432")}/chasqui_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
